---
- name: Generate the configuration files of Logstash from templates
  template:
    src: "{{ item.source }}"
    dest: "{{ logstash_config }}/{{ item.file }}"
    mode: "0644"
    owner: "1000"
    group: "1000"
  loop:
    - file: "config/logstash.yml"
      source: "logstash.yml.j2"
    - file: "config/pipelines.yml"
      source: "pipelines.yml.j2"

- name: Generate pipeline configs
  template:
    src: "{{ item.type }}.conf.j2"
    dest: "{{ logstash_config }}/pipelines/{{ item.name }}_{{ item.id }}.conf"
    mode: "0644"
    owner: "1000"
    group: "1000"
  when: item.enabled == True
  loop: "{{ logstash_pipelines }}"

- name: Generate log4j2.properties for Logstash node
  copy:
    src: "log4j2.properties"
    dest: "{{ logstash_config }}/config/log4j2.properties"
    group: "1000"
    owner: "1000"



