---
# defaults file for elasticsearch
state: "started"
recreate: "no"
firewalld_zone: "public"
timezone: "Europe/Budapest"

# persistent directories
elastic_config: "{{ container_conf_dir }}/{{inventory_hostname_short}}.es_{{elastic.instance_name}}"
elastic_data: "{{ container_data_dir }}/{{inventory_hostname_short}}.es_{{elastic.instance_name}}"
elastic_snapshot_repository: "/mnt/snapshot-repository"

# container or pod networking
elastic_pod_name: "elasticsearch"
elastic_pod_network: "host"

# container defaults
elastic_image: "docker.elastic.co/elasticsearch/elasticsearch"
elastic_version: "{{ elk_version | default(7.14.1)}}"

# cluster settings
elastic_cluster_name: "example.com"
monitoring_cluster: true
monitoring_data_history: 3d

#### Host vars ####
# FIXME the key-pairs should be kept even when they are not changed

elastic:
  hostname: localhost
  instance_name: "master01"
  nodetype: es_master
  ports:
    - "9200"
    - "9300"
  #deployment_type: "single-node"
  noderoles:
    - data
    - master
    - ingest
    - transform
    - remote_cluster_client
  memory_limit: 6g
  cpu_limit: 1
  heap_size: "3g"
  java_opts: "-Xms3g -Xmx3g"
  ip_address: "{{service_ip}}"
  rack_id: A1
  server_room: B1

#### Certificates ####
# Internal Certificate Authority, used to issue internal certificates
cluster_ca_crt: "{{vault_cluster_ca_crt}}"
# Cluster node certificate chain, signed by the CA above. This is installed on all Elasticsearch nodes.
# This is a SAN certificate, listing the names of all of the nodes.
# It is used both for intra-cluster transport encryption and also HTTPS API encryption.
cluster_instance_crt: "{{vault_cluster_instance_crt}}"
# Cluster node key to above certificate. This is installed on all Elasticsearch nodes
# and enable them to encrypt intra-cluster transport communication as well as HTTPS APIs.
cluster_instance_cert_key: "{{vault_cluster_instance_cert_key}}"

# Logstash related certificates:
ssl_cert: "{{ cluster_instance_crt }}"
ssl_key: "{{ cluster_instance_cert_key }}"

# KIBANA related certificates:
# SHOULD BE ACCESSIBLE TO BEATS TOO

# CA certificate (chain) that signed the SSL server certificate used by Kibana
# For now, make it the same as the cluster CA certificate. If it is different, copy the cert here.
kibana_signing_ca_crt: "{{ cluster_ca_crt }}"

# SSL server certificate used by Kibana to encrypt communication
# For now, make it the same as the cluster instance certificate. If it is different, copy the cert here.
kibana_ssl_certificate: "{{ cluster_instance_crt }}"

# SSL server certificate private key used by Kibana to encrypt communication
# For now, make it the same as the vaulted instance certificate key. If it is different, copy the key (preferably vaulted) here.
kibana_ssl_certificate_key: "{{ cluster_instance_cert_key }}"

#### User and role management ####
## The following settings are used by the playbook to connect to Elasticsearch via the HTTP API in order to configure the builtin user passwords
## For the passwords, see the above section.
## This is adapted from the official elasticsearch Ansible playbook found here:
## https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/security/elasticsearch-security-native.yml
es_api_scheme: "https"
es_api_host: "{{groups['elastic_master_nodes'][0]}}"
es_api_port: "{{ elastic.ports[0] }}"
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_api_sleep: 15
es_security_api: "_security"
es_validate_certs: no
es_api_basic_auth_username: "{{elastic_elastic_user}}"
es_api_basic_auth_password: "{{elastic_password}}"
es_delete_unmanaged_file: true
es_delete_unmanaged_native: true

# https://www.elastic.co/guide/en/beats/filebeat/7.15/privileges-to-setup-beats.html
# https://www.elastic.co/guide/en/beats/filebeat/7.15/privileges-to-publish-events.html
# https://www.elastic.co/guide/en/elasticsearch/reference/7.15/built-in-roles.html
es_roles:
  native:
    filebeat_setup:
      cluster:
        - monitor
        - manage_ilm
        - manage_ml
      indices:
        - names: 'filebeat-*'
          privileges:
            - manage
            - write
            - read
    filebeat_writer:
      cluster:
        - monitor
        - read_ilm
        - read_pipeline
      indices:
        - names: 'filebeat-*'
          privileges:
            - create_doc
            - view_index_metadata
            - create_index

es_users:
  native:
    apm_system:
      password: "{{ apm_system_password }}"
    kibana_system:
      password: "{{ kibana_system_password }}"
    logstash_system:
      password: "{{ logstash_system_password }}"
    beats_system:
      password: "{{ beats_system_password }}"
      roles:
        - beats_system
    remote_monitoring_user:
      password: "{{ remote_monitoring_user_password }}"
    filebeat_publisher_user:
      password: "{{ filebeat_publisher_user_password }}"
      roles:
        - filebeat_writer
    filebeat_setup_user:
      password: "{{ filebeat_setup_user_password }}"
      roles:
        - filebeat_setup
        - kibana_admin
        - ingest_admin
        - machine_learning_admin
        - beats_admin
    filebeat_kibana_setup_user:
      password: "{{ filebeat_kibana_setup_user_password }}"
      roles:
        - filebeat_setup
        - kibana_admin

elastic_elastic_user: "elastic"
elastic_password: "{{vault_elastic_password | default(changeMe)}}"
apm_system_password: "{{vault_apm_system_password | default(changeMe)}}"
kibana_system_password: "{{vault_kibana_system_password | default(changeMe)}}"
logstash_system_password: "{{vault_logstash_system_password | default(changeMe)}}"
beats_system_password: "{{vault_beats_system_password | default(changeMe)}}"
remote_monitoring_user_password: "{{vault_remote_monitoring_user_password | default(changeMe)}}"
filebeat_publisher_user_password: "{{vault_filebeat_publisher_user_password | default(changeMe)}}"
filebeat_setup_user_password: "{{vault_filebeat_setup_user_password | default(changeMe)}}"
filebeat_kibana_setup_user_password: "{{vault_filebeat_kibana_setup_user_password | default(changeMe)}}"
