galaxy_info:
  author: Balázs NÉMETH
  description: Runs metricbeat in a pod by podman
  company: balagetech.com

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: OpenSUSE
      versions:
        - 15.3
    - name: CentOS
      versions:
        - 7
        - 8

  galaxy_tags:
    - podman
    - metricbeat

dependencies: []
