---
- name: Copy the certificate used to issue the Elasticsearch node certificates to Kibana servers
  copy:
    content: "{{ item.source }}"
    dest: "{{ kibana_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "1000"
    group: "1000"
  loop:
    - file: ca.crt
      source: "{{ cluster_ca_crt }}"
    - file: kibana_signing_ca.crt
      source: "{{ kibana_signing_ca_crt }}"
    - file: ssl.crt
      source: "{{ kibana_ssl_certificate }}"
    - file: ssl.key
      source: "{{ kibana_ssl_certificate_key }}"
  no_log: true
