---
# tasks file for elasticsearch

- name: Include task sysctlsetup.yml
  include_tasks: "sysctlsetup.yml"

- name: Import createdirs
  include_tasks:
    file: "createdirs.yml"
    apply:
      tags: create_dirs
  tags: create_dirs

- name: Include task generatetemplates.yml
  include_tasks: "generatetemplates.yml"

- name: Include task synccerts.yml
  include_tasks: "synccerts.yml"

# TODO rename this to podman_elasticsearch.yml
- name: Include task elastic_stack_podman.yml
  include_tasks: "elastic_stack_podman.yml"

# https://www.middlewareinventory.com/blog/ansible-dict/#How_to_append_or_add_elements_into_ansible_dictionary
- name: Include custom roles from inventory
  set_fact:
    es_roles: "{{ es_roles | combine(es_roles_custom, recursive=True) }}"
  when: es_roles_custom is defined
  tags: security

- name: Include custom users from inventory
  set_fact:
    es_users: "{{ es_users | combine(es_users_custom, recursive=True) }}"
  when: es_users_custom is defined
  tags: security

- name: Sleep 60 seconds
  pause:
    seconds: 60
  tags: security

# TODO: rename this to match the original filename 'elasticsearch-security-native.yml'
- name: Include task configure_builtin_users_passwords.yml
  include_tasks:
    file: "elasticsearch-security-native.yml"
    apply:
      tags: security
  tags: security
  run_once: True
#  environment:
#    no_proxy: "{{es_api_host}}"
